version: "3"
services:
  docker_fcc:
    ports:
      - 3001:3000
    volumes:
      # bind mount
      - ./:/app
      # avoid unnecessary copying of node_modules
      - /app/node_modules
    env_file:
      - ./.env
    command: npm run dev
